class ModuleContent {
  final String id;
  final String title;
  final String description;
  final List<ModuleSection> sections;

  ModuleContent({
    required this.id,
    required this.title,
    required this.description,
    required this.sections,
  });

  static List<ModuleContent> get sampleModules => [
        ModuleContent(
          id: 'income_tax_basics',
          title: 'Income Tax Basics',
          description: 'Understanding the fundamentals of Income Tax in India.',
          sections: [
            ModuleSection(
              heading: 'What is Income Tax?',
              content:
                  'Income Tax is a direct tax that a government levies on the income of its citizens. The Income Tax Act, 1961 mandates that the central government collect this tax. The government claims the tax on income generated by individuals, Hindu Undivided Families (HUFs), companies, firms, LLPs, etc.',
            ),
            ModuleSection(
              heading: 'Who is liable to pay?',
              content:
                  'Any individual whose total income exceeds the basic exemption limit is required to pay income tax. For the FY 2024-25, under the New Regime, income up to ₹3 Lakhs is exempt from tax.',
            ),
            ModuleSection(
              heading: 'Key Terms',
              content:
                  '• **Assessment Year (AY):** The year in which your income is assessed and taxed (e.g., for income earned in FY 2024-25, the AY is 2025-26).\n• **Financial Year (FY):** The year in which you earn the income (April 1 to March 31).\n• **TDS:** Tax Deducted at Source.',
            ),
          ],
        ),
        ModuleContent(
          id: 'gst_explained',
          title: 'GST Explained',
          description: 'A comprehensive guide to Goods and Services Tax.',
          sections: [
            ModuleSection(
              heading: 'What is GST?',
              content:
                  'GST (Goods and Services Tax) is an indirect tax used in India on the supply of goods and services. It is a comprehensive, multistage, destination-based tax: comprehensive because it has subsumed almost all other indirect taxes except a few state taxes.',
            ),
            ModuleSection(
              heading: 'Components of GST',
              content:
                  '• **CGST:** Collected by the Central Government on an intra-state sale.\n• **SGST:** Collected by the State Government on an intra-state sale.\n• **IGST:** Collected by the Central Government for inter-state sale.',
            ),
          ],
        ),
        ModuleContent(
          id: 'business_registration',
          title: 'Business Registration',
          description: 'How to register your business in India.',
          sections: [
            ModuleSection(
              heading: 'Types of Business Structures',
              content:
                  '• **Sole Proprietorship:** Easiest to start, single owner.\n• **Partnership Firm:** Two or more partners.\n• **LLP (Limited Liability Partnership):** Partners have limited liability.\n• **Private Limited Company:** Separate legal entity, best for startups raising funds.',
            ),
          ],
        ),
        ModuleContent(
          id: 'investment_101',
          title: 'Investment 101',
          description: 'Basics of growing your wealth.',
          sections: [
            ModuleSection(
              heading: 'Why Invest?',
              content:
                  'Investing is essential to beat inflation and grow your wealth over time. Keeping money in a savings account often yields lower returns than inflation.',
            ),
            ModuleSection(
              heading: 'Popular Investment Options',
              content:
                  '• **Fixed Deposits (FD):** Safe, guaranteed returns.\n• **Mutual Funds:** Market-linked, potential for higher returns.\n• **Stocks:** Direct equity, high risk high reward.\n• **Gold:** Hedge against inflation.',
            ),
          ],
        ),
      ];
}

class ModuleSection {
  final String heading;
  final String content;

  ModuleSection({required this.heading, required this.content});
}
